anguage: bash

sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.23.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose -f docker-compose.yml up -d --build

script:
  - docker exec tim6uks_web python manage.py test
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
  - docker tag tim6uks_backend:latest mmilovanovic/tim6uks_backend
  - docker push mmilovanovic/tim6uks_backend
  - docker tag tim6uks_frontend:latest mmilovanovic/tim6uks_frontend
  - docker push mmilovanovic/tim6uks_frontend
  - docker logout 

after_script:
  - docker-compose down

branches:
    only:
    - dev
    - main
 
deploy:
    provider: elasticbeanstalk
    region: eu-central-1
    app: uks-app
    env:  Uksapp-env
    bucket_name: elasticbeanstalk-eu-central-1-661535873995
    bucket_path: uks-app
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on:
        branch: dev
	branch: dockerize-frontend
