version: '3.2'

services:
  web:
    container_name: tim6uks_web
    image: tim6uks_backend:latest
    build:
        context: ./backend
        dockerfile: Dockerfile
    command: ["./wait_for_postgres.sh"]
    ports:
      - 8000:8000
    volumes:
      - ./backend/static:/code/static
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    depends_on:
      - db
  db:
    restart: always
    image: postgres
    container_name: myapp_db
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  nginx:
    image: nginx:latest
    container_name: uks_nginx
    ports:
      - 1234:8000
    volumes:
      - ./backend/config/nginx:/etc/nginx/conf.d
      - ./backend/static:/code/static
      - ../logs:/var/log/nginx
    depends_on:
      - web
  nextjs:
    image: tim6uks_frontend:latest
    container_name: tim6uks_frontend
    build:
        context: ./frontend
        dockerfile: Dockerfile
    command: ["npm", "start"]
    ports:
      - 3000:3000
