# Generated by Django 3.1.5 on 2021-02-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20210215_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
