# Generated by Django 3.1.5 on 2021-01-10 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="Hex color doesn't match pattern", regex='^#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$')]),
        ),
    ]
