# Generated by Django 3.1.5 on 2021-01-10 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('milestone', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('date_opened', models.DateTimeField(auto_now_add=True)),
                ('date_closed', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=20)),
                ('state', models.CharField(choices=[('Opened', 'Opened'), ('Closed', 'Closed')], default='Opened', max_length=20)),
                ('task_status', models.CharField(choices=[('ToDo', 'ToDo'), ('InProgress', 'InProgress'), ('Test', 'Test'), ('Done', 'Done')], default='ToDo', max_length=20)),
                ('assignees', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ManyToManyField(blank=True, to='milestone.Milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
